import Editor from "@monaco-editor/react";

interface Props {
  visible: boolean;
  docs: string;
  onClose: () => void;
  theme: "light" | "dark";
}

// Shows exactly which functions the current task's API tier exposes (name,
// signature, docstring) — generated by ApiBase.combined_doc() for each API
// registered on the environment (see workshop/backend/worker.py). Different
// tasks/tiers expose different function sets (e.g. the reduced tier has no
// get_object_pose(), only plan_grasp() / get_oriented_bounding_box_from_3d_points()),
// so this is meant to answer "what can I actually call here?" without
// guessing from example code written for a different tier.
export default function ApiDocsModal({ visible, docs, onClose, theme }: Props) {
  if (!visible) return null;
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-card" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>利用可能なAPI</h2>
          <button onClick={onClose}>閉じる</button>
        </div>
        <div className="api-docs">
          <Editor
            height="70vh"
            language="python"
            theme={theme === "dark" ? "vs-dark" : "light"}
            value={docs || "# このタスクにはAPIが登録されていません。"}
            options={{
              readOnly: true,
              minimap: { enabled: false },
              scrollBeyondLastLine: false,
              wordWrap: "on",
              padding: { top: 12, bottom: 12 },
              fontSize: 14,
              lineNumbers: "off",
              folding: false,
            }}
          />
        </div>
      </div>
    </div>
  );
}
